/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function generatePrimes(): Buffer
export class CggmpExecutor {
  constructor(sessionId: string, executionId: string, partyIndex: number, threshold: number, partiesCount: number)
  exportKeyshare(): Buffer
  exportAuxInfo(): Buffer
  importKeyshare(data: Buffer): void
  importAuxInfo(data: Buffer): void
  startKeygen(): void
  startAuxGen(): void
  startAuxGenWithPrimes(primesBuf: Buffer): void
  setSigners(json: string): void
  startSigning(txHex: string): void
  step(inputs: Array<Buffer>): Array<Buffer>
  snapshot(): string
  exportKeyshareBin(): Buffer
  exportAuxInfoBin(): Buffer
}
