// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.33.1
// source: proto/cggmp.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";

export const protobufPackage = "cggmp.v1";

export enum Curve {
  CURVE_UNSPECIFIED = 0,
  CURVE_SECP256K1 = 1,
  CURVE_SECP256R1 = 2,
  CURVE_STARK = 3,
  UNRECOGNIZED = -1,
}

export function curveFromJSON(object: any): Curve {
  switch (object) {
    case 0:
    case "CURVE_UNSPECIFIED":
      return Curve.CURVE_UNSPECIFIED;
    case 1:
    case "CURVE_SECP256K1":
      return Curve.CURVE_SECP256K1;
    case 2:
    case "CURVE_SECP256R1":
      return Curve.CURVE_SECP256R1;
    case 3:
    case "CURVE_STARK":
      return Curve.CURVE_STARK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Curve.UNRECOGNIZED;
  }
}

export function curveToJSON(object: Curve): string {
  switch (object) {
    case Curve.CURVE_UNSPECIFIED:
      return "CURVE_UNSPECIFIED";
    case Curve.CURVE_SECP256K1:
      return "CURVE_SECP256K1";
    case Curve.CURVE_SECP256R1:
      return "CURVE_SECP256R1";
    case Curve.CURVE_STARK:
      return "CURVE_STARK";
    case Curve.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Round {
  ROUND_UNSPECIFIED = 0,
  AUX_INFO = 1,
  KEYGEN = 2,
  SIGNING = 3,
  PRESIGNATURE = 4,
  ERROR = 9,
  UNRECOGNIZED = -1,
}

export function roundFromJSON(object: any): Round {
  switch (object) {
    case 0:
    case "ROUND_UNSPECIFIED":
      return Round.ROUND_UNSPECIFIED;
    case 1:
    case "AUX_INFO":
      return Round.AUX_INFO;
    case 2:
    case "KEYGEN":
      return Round.KEYGEN;
    case 3:
    case "SIGNING":
      return Round.SIGNING;
    case 4:
    case "PRESIGNATURE":
      return Round.PRESIGNATURE;
    case 9:
    case "ERROR":
      return Round.ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Round.UNRECOGNIZED;
  }
}

export function roundToJSON(object: Round): string {
  switch (object) {
    case Round.ROUND_UNSPECIFIED:
      return "ROUND_UNSPECIFIED";
    case Round.AUX_INFO:
      return "AUX_INFO";
    case Round.KEYGEN:
      return "KEYGEN";
    case Round.SIGNING:
      return "SIGNING";
    case Round.PRESIGNATURE:
      return "PRESIGNATURE";
    case Round.ERROR:
      return "ERROR";
    case Round.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Envelope {
  version: number;
  sessionId: string;
  executionId: string;
  round: Round;
  fromParty: number;
  toParties: number[];
  meta: Meta | undefined;
  auxInfo?: AuxInfo | undefined;
  keygen?: Keygen | undefined;
  signing?: Signing | undefined;
  presignature?: Presignature | undefined;
  error?: Error | undefined;
  status?: Status | undefined;
}

export interface Meta {
  curve: Curve;
  threshold: number;
  partiesCount: number;
  partyIndex: number;
  txContext: Uint8Array;
  retry: number;
  /** "bincode" (default) or "json" (debug only) */
  payloadFormat: string;
  keyId: string;
}

/** payload는 기본 bincode 직렬화 결과를 base64로 전달하며, 디버그 시(`CGGMP_PAYLOAD_FORMAT=json`) JSON 직렬화를 사용할 수 있습니다. */
export interface AuxInfo {
  payload: Uint8Array;
}

/** 동일한 직렬화 규칙 적용 */
export interface Keygen {
  payload: Uint8Array;
}

export interface Signing {
  /** Msg serialize (prost bytes) */
  payload: Uint8Array;
  /** required; raw digest/digest hash */
  txContext: Uint8Array;
}

export interface Presignature {
  /** Msg serialize (prost bytes) */
  payload: Uint8Array;
}

export interface Error {
  code: number;
  message: string;
  retriable: boolean;
}

export interface Status {
  /** 200: OK (with data), 201: Finished */
  code: number;
  /** JSON encoded data (publicKey, etc.) or status string */
  message: string;
  /** "keygen_finished", "aux_gen_finished", etc. */
  status: string;
}

function createBaseEnvelope(): Envelope {
  return {
    version: 0,
    sessionId: "",
    executionId: "",
    round: 0,
    fromParty: 0,
    toParties: [],
    meta: undefined,
    auxInfo: undefined,
    keygen: undefined,
    signing: undefined,
    presignature: undefined,
    error: undefined,
    status: undefined,
  };
}

export const Envelope = {
  encode(message: Envelope, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.version !== 0) {
      writer.uint32(8).uint32(message.version);
    }
    if (message.sessionId !== "") {
      writer.uint32(18).string(message.sessionId);
    }
    if (message.executionId !== "") {
      writer.uint32(26).string(message.executionId);
    }
    if (message.round !== 0) {
      writer.uint32(32).int32(message.round);
    }
    if (message.fromParty !== 0) {
      writer.uint32(40).uint32(message.fromParty);
    }
    writer.uint32(50).fork();
    for (const v of message.toParties) {
      writer.uint32(v);
    }
    writer.ldelim();
    if (message.meta !== undefined) {
      Meta.encode(message.meta, writer.uint32(58).fork()).ldelim();
    }
    if (message.auxInfo !== undefined) {
      AuxInfo.encode(message.auxInfo, writer.uint32(82).fork()).ldelim();
    }
    if (message.keygen !== undefined) {
      Keygen.encode(message.keygen, writer.uint32(90).fork()).ldelim();
    }
    if (message.signing !== undefined) {
      Signing.encode(message.signing, writer.uint32(98).fork()).ldelim();
    }
    if (message.presignature !== undefined) {
      Presignature.encode(message.presignature, writer.uint32(106).fork()).ldelim();
    }
    if (message.error !== undefined) {
      Error.encode(message.error, writer.uint32(114).fork()).ldelim();
    }
    if (message.status !== undefined) {
      Status.encode(message.status, writer.uint32(122).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Envelope {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnvelope();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.version = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.executionId = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.round = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.fromParty = reader.uint32();
          continue;
        case 6:
          if (tag === 48) {
            message.toParties.push(reader.uint32());

            continue;
          }

          if (tag === 50) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.toParties.push(reader.uint32());
            }

            continue;
          }

          break;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.meta = Meta.decode(reader, reader.uint32());
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.auxInfo = AuxInfo.decode(reader, reader.uint32());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.keygen = Keygen.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.signing = Signing.decode(reader, reader.uint32());
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.presignature = Presignature.decode(reader, reader.uint32());
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.error = Error.decode(reader, reader.uint32());
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.status = Status.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Envelope {
    return {
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      sessionId: isSet(object.sessionId) ? globalThis.String(object.sessionId) : "",
      executionId: isSet(object.executionId) ? globalThis.String(object.executionId) : "",
      round: isSet(object.round) ? roundFromJSON(object.round) : 0,
      fromParty: isSet(object.fromParty) ? globalThis.Number(object.fromParty) : 0,
      toParties: globalThis.Array.isArray(object?.toParties)
        ? object.toParties.map((e: any) => globalThis.Number(e))
        : [],
      meta: isSet(object.meta) ? Meta.fromJSON(object.meta) : undefined,
      auxInfo: isSet(object.auxInfo) ? AuxInfo.fromJSON(object.auxInfo) : undefined,
      keygen: isSet(object.keygen) ? Keygen.fromJSON(object.keygen) : undefined,
      signing: isSet(object.signing) ? Signing.fromJSON(object.signing) : undefined,
      presignature: isSet(object.presignature) ? Presignature.fromJSON(object.presignature) : undefined,
      error: isSet(object.error) ? Error.fromJSON(object.error) : undefined,
      status: isSet(object.status) ? Status.fromJSON(object.status) : undefined,
    };
  },

  toJSON(message: Envelope): unknown {
    const obj: any = {};
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.executionId !== "") {
      obj.executionId = message.executionId;
    }
    if (message.round !== 0) {
      obj.round = roundToJSON(message.round);
    }
    if (message.fromParty !== 0) {
      obj.fromParty = Math.round(message.fromParty);
    }
    if (message.toParties?.length) {
      obj.toParties = message.toParties.map((e) => Math.round(e));
    }
    if (message.meta !== undefined) {
      obj.meta = Meta.toJSON(message.meta);
    }
    if (message.auxInfo !== undefined) {
      obj.auxInfo = AuxInfo.toJSON(message.auxInfo);
    }
    if (message.keygen !== undefined) {
      obj.keygen = Keygen.toJSON(message.keygen);
    }
    if (message.signing !== undefined) {
      obj.signing = Signing.toJSON(message.signing);
    }
    if (message.presignature !== undefined) {
      obj.presignature = Presignature.toJSON(message.presignature);
    }
    if (message.error !== undefined) {
      obj.error = Error.toJSON(message.error);
    }
    if (message.status !== undefined) {
      obj.status = Status.toJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Envelope>, I>>(base?: I): Envelope {
    return Envelope.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Envelope>, I>>(object: I): Envelope {
    const message = createBaseEnvelope();
    message.version = object.version ?? 0;
    message.sessionId = object.sessionId ?? "";
    message.executionId = object.executionId ?? "";
    message.round = object.round ?? 0;
    message.fromParty = object.fromParty ?? 0;
    message.toParties = object.toParties?.map((e) => e) || [];
    message.meta = (object.meta !== undefined && object.meta !== null) ? Meta.fromPartial(object.meta) : undefined;
    message.auxInfo = (object.auxInfo !== undefined && object.auxInfo !== null)
      ? AuxInfo.fromPartial(object.auxInfo)
      : undefined;
    message.keygen = (object.keygen !== undefined && object.keygen !== null)
      ? Keygen.fromPartial(object.keygen)
      : undefined;
    message.signing = (object.signing !== undefined && object.signing !== null)
      ? Signing.fromPartial(object.signing)
      : undefined;
    message.presignature = (object.presignature !== undefined && object.presignature !== null)
      ? Presignature.fromPartial(object.presignature)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null) ? Error.fromPartial(object.error) : undefined;
    message.status = (object.status !== undefined && object.status !== null)
      ? Status.fromPartial(object.status)
      : undefined;
    return message;
  },
};

function createBaseMeta(): Meta {
  return {
    curve: 0,
    threshold: 0,
    partiesCount: 0,
    partyIndex: 0,
    txContext: new Uint8Array(0),
    retry: 0,
    payloadFormat: "",
    keyId: "",
  };
}

export const Meta = {
  encode(message: Meta, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.curve !== 0) {
      writer.uint32(8).int32(message.curve);
    }
    if (message.threshold !== 0) {
      writer.uint32(16).uint32(message.threshold);
    }
    if (message.partiesCount !== 0) {
      writer.uint32(24).uint32(message.partiesCount);
    }
    if (message.partyIndex !== 0) {
      writer.uint32(32).uint32(message.partyIndex);
    }
    if (message.txContext.length !== 0) {
      writer.uint32(42).bytes(message.txContext);
    }
    if (message.retry !== 0) {
      writer.uint32(48).uint32(message.retry);
    }
    if (message.payloadFormat !== "") {
      writer.uint32(58).string(message.payloadFormat);
    }
    if (message.keyId !== "") {
      writer.uint32(66).string(message.keyId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Meta {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMeta();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.curve = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.threshold = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.partiesCount = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.partyIndex = reader.uint32();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.txContext = reader.bytes();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.retry = reader.uint32();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.payloadFormat = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.keyId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Meta {
    return {
      curve: isSet(object.curve) ? curveFromJSON(object.curve) : 0,
      threshold: isSet(object.threshold) ? globalThis.Number(object.threshold) : 0,
      partiesCount: isSet(object.partiesCount) ? globalThis.Number(object.partiesCount) : 0,
      partyIndex: isSet(object.partyIndex) ? globalThis.Number(object.partyIndex) : 0,
      txContext: isSet(object.txContext) ? bytesFromBase64(object.txContext) : new Uint8Array(0),
      retry: isSet(object.retry) ? globalThis.Number(object.retry) : 0,
      payloadFormat: isSet(object.payloadFormat) ? globalThis.String(object.payloadFormat) : "",
      keyId: isSet(object.keyId) ? globalThis.String(object.keyId) : "",
    };
  },

  toJSON(message: Meta): unknown {
    const obj: any = {};
    if (message.curve !== 0) {
      obj.curve = curveToJSON(message.curve);
    }
    if (message.threshold !== 0) {
      obj.threshold = Math.round(message.threshold);
    }
    if (message.partiesCount !== 0) {
      obj.partiesCount = Math.round(message.partiesCount);
    }
    if (message.partyIndex !== 0) {
      obj.partyIndex = Math.round(message.partyIndex);
    }
    if (message.txContext.length !== 0) {
      obj.txContext = base64FromBytes(message.txContext);
    }
    if (message.retry !== 0) {
      obj.retry = Math.round(message.retry);
    }
    if (message.payloadFormat !== "") {
      obj.payloadFormat = message.payloadFormat;
    }
    if (message.keyId !== "") {
      obj.keyId = message.keyId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Meta>, I>>(base?: I): Meta {
    return Meta.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Meta>, I>>(object: I): Meta {
    const message = createBaseMeta();
    message.curve = object.curve ?? 0;
    message.threshold = object.threshold ?? 0;
    message.partiesCount = object.partiesCount ?? 0;
    message.partyIndex = object.partyIndex ?? 0;
    message.txContext = object.txContext ?? new Uint8Array(0);
    message.retry = object.retry ?? 0;
    message.payloadFormat = object.payloadFormat ?? "";
    message.keyId = object.keyId ?? "";
    return message;
  },
};

function createBaseAuxInfo(): AuxInfo {
  return { payload: new Uint8Array(0) };
}

export const AuxInfo = {
  encode(message: AuxInfo, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.payload.length !== 0) {
      writer.uint32(10).bytes(message.payload);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AuxInfo {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuxInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.payload = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuxInfo {
    return { payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0) };
  },

  toJSON(message: AuxInfo): unknown {
    const obj: any = {};
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuxInfo>, I>>(base?: I): AuxInfo {
    return AuxInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuxInfo>, I>>(object: I): AuxInfo {
    const message = createBaseAuxInfo();
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function createBaseKeygen(): Keygen {
  return { payload: new Uint8Array(0) };
}

export const Keygen = {
  encode(message: Keygen, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.payload.length !== 0) {
      writer.uint32(10).bytes(message.payload);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Keygen {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeygen();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.payload = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Keygen {
    return { payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0) };
  },

  toJSON(message: Keygen): unknown {
    const obj: any = {};
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Keygen>, I>>(base?: I): Keygen {
    return Keygen.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Keygen>, I>>(object: I): Keygen {
    const message = createBaseKeygen();
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSigning(): Signing {
  return { payload: new Uint8Array(0), txContext: new Uint8Array(0) };
}

export const Signing = {
  encode(message: Signing, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.payload.length !== 0) {
      writer.uint32(10).bytes(message.payload);
    }
    if (message.txContext.length !== 0) {
      writer.uint32(18).bytes(message.txContext);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Signing {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSigning();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.txContext = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Signing {
    return {
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
      txContext: isSet(object.txContext) ? bytesFromBase64(object.txContext) : new Uint8Array(0),
    };
  },

  toJSON(message: Signing): unknown {
    const obj: any = {};
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.txContext.length !== 0) {
      obj.txContext = base64FromBytes(message.txContext);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Signing>, I>>(base?: I): Signing {
    return Signing.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Signing>, I>>(object: I): Signing {
    const message = createBaseSigning();
    message.payload = object.payload ?? new Uint8Array(0);
    message.txContext = object.txContext ?? new Uint8Array(0);
    return message;
  },
};

function createBasePresignature(): Presignature {
  return { payload: new Uint8Array(0) };
}

export const Presignature = {
  encode(message: Presignature, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.payload.length !== 0) {
      writer.uint32(10).bytes(message.payload);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Presignature {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePresignature();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.payload = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Presignature {
    return { payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0) };
  },

  toJSON(message: Presignature): unknown {
    const obj: any = {};
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Presignature>, I>>(base?: I): Presignature {
    return Presignature.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Presignature>, I>>(object: I): Presignature {
    const message = createBasePresignature();
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function createBaseError(): Error {
  return { code: 0, message: "", retriable: false };
}

export const Error = {
  encode(message: Error, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.code !== 0) {
      writer.uint32(8).uint32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.retriable !== false) {
      writer.uint32(24).bool(message.retriable);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Error {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseError();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.code = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.retriable = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Error {
    return {
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      retriable: isSet(object.retriable) ? globalThis.Boolean(object.retriable) : false,
    };
  },

  toJSON(message: Error): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.retriable !== false) {
      obj.retriable = message.retriable;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Error>, I>>(base?: I): Error {
    return Error.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Error>, I>>(object: I): Error {
    const message = createBaseError();
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.retriable = object.retriable ?? false;
    return message;
  },
};

function createBaseStatus(): Status {
  return { code: 0, message: "", status: "" };
}

export const Status = {
  encode(message: Status, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.code !== 0) {
      writer.uint32(8).uint32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Status {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.code = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.status = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Status {
    return {
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: Status): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Status>, I>>(base?: I): Status {
    return Status.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Status>, I>>(object: I): Status {
    const message = createBaseStatus();
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

export interface CggmpNode {
  Session(request: Observable<Envelope>): Observable<Envelope>;
}

export const CggmpNodeServiceName = "cggmp.v1.CggmpNode";
export class CggmpNodeClientImpl implements CggmpNode {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || CggmpNodeServiceName;
    this.rpc = rpc;
    this.Session = this.Session.bind(this);
  }
  Session(request: Observable<Envelope>): Observable<Envelope> {
    const data = request.pipe(map((request) => Envelope.encode(request).finish()));
    const result = this.rpc.bidirectionalStreamingRequest(this.service, "Session", data);
    return result.pipe(map((data) => Envelope.decode(_m0.Reader.create(data))));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
  clientStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Promise<Uint8Array>;
  serverStreamingRequest(service: string, method: string, data: Uint8Array): Observable<Uint8Array>;
  bidirectionalStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Observable<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
